server:
  port: 8000

spring:
  application:
    name: trysprinigcloud-netflix-eureka-clientone

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false