server:
  port: 8888

spring:
  application:
    name: trysprinigcloud-security
  data:
    mongodb:
      uri: mongodb://localhost:27017/accountService

spring.se  security:


jwt:
  secret: mySecret
  expiration: 604800